### ISSUE TITLE
2 Features suggest

### ISSUE THREAD

**Issue by Espinete1987** [Tallcraft/DeathBarrel#12] opened 2021-06-12 06:03 UTC
Hello Tallcraft, i would like to ask you to add some features please. Im using 1.15.2
What i want to ask you is, either being in pvp or pve, the other players can open the barrels of the other persons, so i really would like to add a option like "players open barrels of other players: deny"
Becouse i cant control the crazy people in my server, not all of them are respectfull

Also i would like to ask for add the feature of select which items can be drop, for example to choose between inventory or belt, or even in inventory choose the first row.
This plugin is great but i cant activate the pvp in my server due i want to restrict a bit what they can loose when they die.

Thanks again, is not the first time that you listen to me, i suggested the feature to remove when empty, nice job  ;)

**Comment by Trikolon** [comment] 2021-06-12 13:00
The protection part is a dupe of #11 and was  implemented in the latest release `v1.4.0`.
For only having players drop parts of their inventory I suggest you use a different plugin. Doesn't fit into the scope of this one. If you run into compatibility issues please file an issue though.

**Closed as completed by Trikolon** 2021-06-12 13:00 UTC
Labels: duplicate, wontfix
